apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'misibot-app'
        static_configs:
          - targets: ['misibot-app-service:3000']
      - job_name: 'postgres'
        static_configs:
          - targets: ['postgres-service:5432']
      - job_name: 'mongodb'
        static_configs:
          - targets: ['mongodb-service:27017']
      - job_name: 'redis'
        static_configs:
          - targets: ['redis-service:6379']